### ISSUE TITLE
Using delete button to delete items

### ISSUE THREAD

**Issue by SubhadeepJasu** [Philip-Scott/Spice-up#247]
Currently only the dust bin button is used to delete items, it would be better to have the delete key be used to delete buttons as well.

**Comment by Philip-Scott** [comment]
Ctrl+Delete or backspace deletes the selected item :)

**Comment by aleksandar-stefanovic** [comment]
It isn't intuitive, though: I tried the delete key, and it didn't work, so I guessed it wasn't yet implemented, especially seeing that Delete key does nothing at the moment. I guess I'm not the only one, and that there are a lot of non-tech-savvy users who wouldn't figure out Ctrl+Delete, either. 99% of the software I used, use Delete as an key to trigger "delete selected item" action, and not the Ctrl+Delete (so I guess people expect one behavior over the other).

I've committed this in my fork, I can do a pull request if you want.

Or at least somehow make it easier to discover the shortcut (maybe shortcut hints recently added to the tooltip with Juno?).

**Comment by SubhadeepJasu** [comment]
There is no way for the user to know that ctrl+delete should be used. As mentioned above, its counter intuitive. Understandably an user might assume that the delete button doesn't work here. 'Delete' is an universal key to delete something. Now that we know the ctrl + delete deletes stuff in this app, the issue still isn't invalid. Its just something we know, but majority of users outside of this conversation may not know. My issue wasn't that there is no keyboard accelerator to delete items, but using the "delete" key to delete items.

**Comment by SubhadeepJasu** [comment]
Anyways, no harsh feelings here. Its just something, you could consider. The user is drunk ;)

**Comment by Philip-Scott** [comment]
The reason Ctrl+Delete is used is to make it consistent and so you can always delete items. Just pressing delete conflicts with deleting text.

The shortcut hints thought is something that could be added though, for that and to every other shortcut out there :) Gotta wait for the stable release of Granite though
